# Chordroid

Chordroid is a simple, free app that uses your phone's microphone to listen to live music and automatically detect what chords are being played.  It can be used as an aid to learn new songs, follow along with jam sessions, or to help learn an instrument.  Five types of chord are distinguished - major, minor, dimished, augmented, and suspended.

Three chords are displayed in the view.  In the middle is the current chord detected.  To the left is the previous chord detected, and to the right is the predicted next chord.  Beneath each chord is a bar which shows how confident the detector is.

Chordroid is written in Java using the IntelliJ Idea IDE.